# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bindings', [dirname(__file__)])
        except ImportError:
            import _bindings
            return _bindings
        if fp is not None:
            try:
                _mod = imp.load_module('_bindings', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bindings = swig_import_helper()
    del swig_import_helper
else:
    import _bindings
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Middle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Middle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Middle, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _bindings.new_Middle(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _bindings.delete_Middle
    __del__ = lambda self: None

    def getMid1(self):
        return _bindings.Middle_getMid1(self)

    def setMid1(self, v):
        return _bindings.Middle_setMid1(self, v)

    def getMid2(self):
        return _bindings.Middle_getMid2(self)

    def setMid2(self, v):
        return _bindings.Middle_setMid2(self, v)

    def getInner(self):
        return _bindings.Middle_getInner(self)

    def setInner(self, v):
        return _bindings.Middle_setInner(self, v)

    def write(self, *args):
        return _bindings.Middle_write(self, *args)

    def read(self, *args):
        return _bindings.Middle_read(self, *args)
Middle_swigregister = _bindings.Middle_swigregister
Middle_swigregister(Middle)

# This file is compatible with both classic and new-style classes.


